### ISSUE TITLE
hrmprint: consider with open() as f: syntax for writing file

### ISSUE THREAD

**Issue by mlp6** [btlee215/bme590hrm#19]

**Comment by aes88** [comment]
I got this to work, but I'm not sure why this is better than the method we used previously

**Comment by mlp6** [comment]
"Better" is debatable.  The primary benefit is that it handles the file closure more elegantly if an exception is raised (i.e., python attempts to more gracefully close the file when the `with` chunk of code ends); if you don't use `with`, then your code may never get to the `close()` line, leaving the file in an ambiguous state.  Some more details here: https://www.python.org/dev/peps/pep-0343/
